spring:
  cloud:
    function:
      definition: producerSupplier; processorFunction; consumer;
    stream:
      bindings:
        producerSupplier-out-0:
          destination: intermediate-topic
        processorFunction-in-0:
          destination: intermediate-topic
          group: consumer-group
        processorFunction-out-0:
          destination: final-topic
          group: consumer-group
        consumer-in-0:
          destination: final-topic
          group: consumer-group
      kafka:
        bindings:
          consumer-in-0:
            consumer:
              ackMode: MANUAL_IMMEDIATE


